/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gov_nih_nlm_ner_gnormplus_CRFTestJNI */

#ifndef _Included_gov_nih_nlm_ner_gnormplus_CRFTestJNI
#define _Included_gov_nih_nlm_ner_gnormplus_CRFTestJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gov_nih_nlm_ner_gnormplus_CRFTestJNI
 * Method:    crftest
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_nih_nlm_ner_gnormplus_CRFTestJNI_crftest
  (JNIEnv *, jobject, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
